server {
    listen 80;
    index index.php index.html;
    server_name localhost;

    root /var/www/public;

    # Laravelのルーティング用
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP処理
    location ~ \.php$ {
        fastcgi_pass app:9000; # appコンテナに接続
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # セキュリティ
    location ~ /\.ht {
        deny all;
    }
}